apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::149033189183:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LEOUC1F1HOMH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::149033189183:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-06T11:35:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1550"
  uid: 2f131d6b-b629-434c-9670-d601dcba238b
